Update UnityEditorShell.cs
"UnityEditorShell.cs(112,13): error CS0103: The name 'start' does not exist in the current context"

Making the proposed change allows your example code to run properly in Unity 2022.3.22f1